module.exports = [
    "Constantly plays with a coin",
    "Bites their nails",
    "Chain smoker",
    "Has a lisp",
    "Extremely squeamish about blood",
    "Constantly quotes movies",
    "Covered in tattoos",
    "Whistles to fill the silence",
    "Chuckles after everything they say",
    "Constantly anthropomorphizes things",
    "Loves animals",
    "Absolute night owl",
    "Always sits up straight",
    "Chews pens/pencils/quills",
    "Deeply afraid of sailing/flying",
    "Fear of heights",
    "Likes things in threes",
    "Eats when they're stressed",
    "Impossibly high alcohol tolerance",
    "Doesn't appreciate art",
    "Constantly loses focus and daydreams",
    "Constantly cracks knuckles/neck",
    "Really exaggerated yawn",
    "Keeps an extremely precise schedule",
    "Loud",
    "Puts a ton of spices in their food",
    "Twirls their hair",
    "Tons of piercings",
    "Resents being interrupted",
    "Bad relationship with their sibling(s)",
    "Gallows humor",
    "Unusual haircut",
    "Doesn't like to wear shoes",
]