module.exports = [
    "Constantly plays with a coin",
    "Bites their nails",
    "Chain smoker",
    "Has a lisp",
    "Extremely squeamish about blood",
    "Constantly quotes movies",
    "Covered in tattoos",
    "Whistles to fill the silence",
    "Chuckles after everything they say",
    "Constantly anthropomorphizes things",
    "Loves animals",
    "Absolute night owl",
    "Always sits up straight",
    "Chews pens/pencils/quills",
    "Deeply afraid of sailing/flying",
    "Fear of heights",
    "Likes things in threes",
    "Eats when they're stressed",
    "Impossibly high alcohol tolerance",
    "Doesn't appreciate art",
    "Constantly loses focus and daydreams",
    "Constantly cracks knuckles/neck",
    "Really exaggerated yawn",
    "Keeps an extremely precise schedule",
    "Loud",
    "Puts a ton of spices in their food",
    "Twirls their hair",
    "Tons of piercings",
    "Resents being interrupted",
    "Bad relationship with their sibling(s)",
    "Gallows humor",
    "Unusual haircut",
    "Doesn't like to wear shoes",
    "In a cult/has unusual religious beliefs",
    "Encyclopedic knowledge of plants",
    "Always has a knife",
    "Reflexively flirty",
    "Deep sense of familial pride",
    "Thinks people are talking behind their back",
    "Deep sense of entitlement",
    "Thrill-seeker",
    "Hedonist",
    "Obsession/fascination with a culture other than their own",
    "Quick to cry",
    "Explosive temper",
    "Sensitive to bright light",
    "Wears an outlandish pair of glasses",
    "Shock of white hair",
    "Unusually tall",
    "Old-fashioned",
    "Deadpan tone of voice",
    "Exaggerates everything",
    "Chronically tells little white lies",
    "Disorganized",
    "Exceedingly dry lips",
    "Gambles on everything",
    "Constantly drunk",
    "Extremely curious",
    "Constantly taps out a rhythm",
]